using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
namespace RestaurantPos.Infrastructure.Migrations;

[DbContext(typeof(RestaurantDbContext))]
[Migration("202608110001_InitialCreate")]
public partial class InitialCreate : Migration
{
    protected override void Up(MigrationBuilder m)
    {
        m.CreateTable(name: "Users", columns: t => new { Id = t.Column<int>(nullable: false).Annotation("Sqlite:Autoincrement", true), DisplayName = t.Column<string>(maxLength: 100, nullable: false), PinHash = t.Column<string>(maxLength: 255, nullable: false), Role = t.Column<int>(nullable: false), IsActive = t.Column<bool>(nullable: false), CreatedUtc = t.Column<DateTime>(nullable: false) }, constraints: c => c.PrimaryKey("PK_Users", x => x.Id));
        m.CreateTable(name: "DiningTables", columns: t => new { Id = t.Column<int>(nullable: false).Annotation("Sqlite:Autoincrement", true), Name = t.Column<string>(maxLength: 40, nullable: false), Capacity = t.Column<int>(nullable: false), IsActive = t.Column<bool>(nullable: false) }, constraints: c => c.PrimaryKey("PK_DiningTables", x => x.Id));
        m.CreateTable(name: "MenuCategories", columns: t => new { Id = t.Column<int>(nullable: false).Annotation("Sqlite:Autoincrement", true), Name = t.Column<string>(maxLength: 80, nullable: false), SortOrder = t.Column<int>(nullable: false), IsActive = t.Column<bool>(nullable: false) }, constraints: c => c.PrimaryKey("PK_MenuCategories", x => x.Id));
        m.CreateTable(name: "AuditEntries", columns: t => new { Id = t.Column<long>(nullable: false).Annotation("Sqlite:Autoincrement", true), UserId = t.Column<int>(nullable: true), Action = t.Column<int>(nullable: false), EntityType = t.Column<string>(maxLength: 80, nullable: false), EntityId = t.Column<string>(maxLength: 80, nullable: false), Detail = t.Column<string>(maxLength: 500, nullable: false), OccurredUtc = t.Column<DateTime>(nullable: false) }, constraints: c => c.PrimaryKey("PK_AuditEntries", x => x.Id));
        m.CreateTable(name: "MenuItems", columns: t => new { Id = t.Column<int>(nullable: false).Annotation("Sqlite:Autoincrement", true), MenuCategoryId = t.Column<int>(nullable: false), Name = t.Column<string>(maxLength: 120, nullable: false), UnitPrice = t.Column<decimal>(type: "TEXT", precision: 18, scale: 2, nullable: false), GstRate = t.Column<decimal>(type: "TEXT", precision: 5, scale: 2, nullable: false), IsActive = t.Column<bool>(nullable: false), SortOrder = t.Column<int>(nullable: false) }, constraints: c => { c.PrimaryKey("PK_MenuItems", x => x.Id); c.ForeignKey("FK_MenuItems_MenuCategories_MenuCategoryId", x => x.MenuCategoryId, "MenuCategories", "Id", onDelete: ReferentialAction.Restrict); });
        m.CreateTable(name: "Orders", columns: t => new { Id = t.Column<int>(nullable: false).Annotation("Sqlite:Autoincrement", true), InvoiceNumber = t.Column<string>(maxLength: 40, nullable: false), Type = t.Column<int>(nullable: false), Status = t.Column<int>(nullable: false), DiningTableId = t.Column<int>(nullable: true), CreatedByUserId = t.Column<int>(nullable: false), OpenedUtc = t.Column<DateTime>(nullable: false), ClosedUtc = t.Column<DateTime>(nullable: true), Notes = t.Column<string>(nullable: true), DiscountAmount = t.Column<decimal>(type: "TEXT", precision: 18, scale: 2, nullable: false), TaxAmount = t.Column<decimal>(type: "TEXT", precision: 18, scale: 2, nullable: false), GrandTotal = t.Column<decimal>(type: "TEXT", precision: 18, scale: 2, nullable: false) }, constraints: c => { c.PrimaryKey("PK_Orders", x => x.Id); c.ForeignKey("FK_Orders_DiningTables_DiningTableId", x => x.DiningTableId, "DiningTables", "Id", onDelete: ReferentialAction.Restrict); c.ForeignKey("FK_Orders_Users_CreatedByUserId", x => x.CreatedByUserId, "Users", "Id", onDelete: ReferentialAction.Restrict); });
        m.CreateTable(name: "OrderLines", columns: t => new { Id = t.Column<int>(nullable: false).Annotation("Sqlite:Autoincrement", true), OrderId = t.Column<int>(nullable: false), MenuItemId = t.Column<int>(nullable: false), ItemName = t.Column<string>(maxLength: 120, nullable: false), UnitPrice = t.Column<decimal>(type: "TEXT", precision: 18, scale: 2, nullable: false), GstRate = t.Column<decimal>(type: "TEXT", precision: 5, scale: 2, nullable: false), Quantity = t.Column<decimal>(type: "TEXT", precision: 10, scale: 2, nullable: false), DiscountType = t.Column<int>(nullable: false), DiscountValue = t.Column<decimal>(type: "TEXT", precision: 18, scale: 2, nullable: false), TaxAmount = t.Column<decimal>(type: "TEXT", precision: 18, scale: 2, nullable: false), LineTotal = t.Column<decimal>(type: "TEXT", precision: 18, scale: 2, nullable: false) }, constraints: c => { c.PrimaryKey("PK_OrderLines", x => x.Id); c.ForeignKey("FK_OrderLines_Orders_OrderId", x => x.OrderId, "Orders", "Id", onDelete: ReferentialAction.Cascade); });
        m.CreateTable(name: "Payments", columns: t => new { Id = t.Column<int>(nullable: false).Annotation("Sqlite:Autoincrement", true), OrderId = t.Column<int>(nullable: false), Method = t.Column<int>(nullable: false), Amount = t.Column<decimal>(type: "TEXT", precision: 18, scale: 2, nullable: false), Reference = t.Column<string>(maxLength: 100, nullable: true), PaidUtc = t.Column<DateTime>(nullable: false) }, constraints: c => { c.PrimaryKey("PK_Payments", x => x.Id); c.ForeignKey("FK_Payments_Orders_OrderId", x => x.OrderId, "Orders", "Id", onDelete: ReferentialAction.Cascade); });
        m.CreateIndex("IX_Users_DisplayName", "Users", "DisplayName", unique: true); m.CreateIndex("IX_DiningTables_Name", "DiningTables", "Name", unique: true); m.CreateIndex("IX_MenuCategories_Name", "MenuCategories", "Name", unique: true); m.CreateIndex("IX_MenuItems_MenuCategoryId", "MenuItems", "MenuCategoryId"); m.CreateIndex("IX_Orders_InvoiceNumber", "Orders", "InvoiceNumber", unique: true); m.CreateIndex("IX_Orders_Status_OpenedUtc", "Orders", new[] { "Status", "OpenedUtc" }); m.CreateIndex("IX_Orders_DiningTableId", "Orders", "DiningTableId"); m.CreateIndex("IX_Orders_CreatedByUserId", "Orders", "CreatedByUserId"); m.CreateIndex("IX_OrderLines_OrderId", "OrderLines", "OrderId"); m.CreateIndex("IX_Payments_OrderId", "Payments", "OrderId"); m.CreateIndex("IX_AuditEntries_EntityType_EntityId", "AuditEntries", new[] { "EntityType", "EntityId" }); m.CreateIndex("IX_AuditEntries_OccurredUtc", "AuditEntries", "OccurredUtc");
    }
    protected override void Down(MigrationBuilder m) { m.DropTable("AuditEntries"); m.DropTable("MenuItems"); m.DropTable("OrderLines"); m.DropTable("Payments"); m.DropTable("Orders"); m.DropTable("MenuCategories"); m.DropTable("DiningTables"); m.DropTable("Users"); }
}
